# Generated by Django 5.2.17 on 2026-09-08 00:27

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_processedstripeevent_stripe_checkout_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditledger',
            name='refund_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='billing.creditledger'),
        ),
        migrations.CreateModel(
            name='AIJobReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=32)),
                ('job_key', models.CharField(max_length=160)),
                ('allowed_units', models.PositiveIntegerField()),
                ('units_per_credit', models.PositiveIntegerField()),
                ('reserved_credits', models.PositiveIntegerField()),
                ('started_units', models.PositiveIntegerField(default=0)),
                ('completed_units', models.PositiveIntegerField(default=0)),
                ('successful_units', models.PositiveIntegerField(default=0)),
                ('charged_credits', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=80)),
                ('debit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='billing.creditledger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_job_reservation',
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['status', 'expires_at'], name='ai_job_recovery_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'job_key'), name='uniq_ai_job_attempt'), models.CheckConstraint(condition=models.Q(('units_per_credit__gt', 0)), name='ai_job_positive_rate'), models.CheckConstraint(condition=models.Q(('allowed_units__gt', 0)), name='ai_job_positive_units'), models.CheckConstraint(condition=models.Q(('started_units__lte', models.F('allowed_units'))), name='ai_job_start_bound'), models.CheckConstraint(condition=models.Q(('completed_units__lte', models.F('started_units'))), name='ai_job_complete_bound'), models.CheckConstraint(condition=models.Q(('successful_units__lte', models.F('completed_units'))), name='ai_job_success_bound'), models.CheckConstraint(condition=models.Q(('charged_credits__lte', models.F('reserved_credits'))), name='ai_job_charge_bound')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
