# Generated by Django 5.2.17 on 2026-09-08 00:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_creditledger_refund_of_aijobreservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aijobreservation',
            index=models.Index(fields=['user', 'created'], name='ai_job_admission_idx'),
        ),
        migrations.AddIndex(
            model_name='aijobreservation',
            index=models.Index(fields=['user', 'expires_at'], name='ai_job_attempt_window_idx'),
        ),
    ]
